baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "nightfall"

[params]
author = "VinKon's Blog"
user = "Vinkon"
hostname = "lilkon.cn"

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/Blackwen"

[[params.social]]
key = 1
name = "Facebook"
url = "https://www.facebook.com/p/Kon-Vin-100094302025735/"

[[params.social]]
key = 2
name = "Bilibili"
url = "https://space.bilibili.com/672629902"

[[params.social]]
key = 3
name = "Email"
url = "mailto:black1201wk@outlook.com"

[[params.social]]
key = 4
name = "More"
url = ""

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"  



















